# Generated by Django 3.2.4 on 2022-07-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txbed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aohsfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
