# Generated by Django 3.1.7 on 2021-03-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create time')),
                ('file_name', models.CharField(max_length=256)),
                ('delete', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
