# Generated by Django 3.2.4 on 2022-07-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videohistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
